apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s
  labels:
    name: springboot-k8s
spec:
  ports:
   - nodePort: 30163
     port: 8081
     targetPort: k8s-port
     protocol: TCP
  selector:
    app: springboot-k8s
  type: NodePort 
